export const users = [
  {
    key: 1,
    name: "Curran Brown",
    email: "Wilkins@moebiuslogistics.co",
    date_of_birth: "21 Dec 1973",
    position: "Director of Market Center",
    department: "Market Center",
    salary: '35000',
    contract_type: 'Fixed-term',
    employment_date: '19 Dec 2010',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 10.8,
    compa_ratio: 90.4,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 2,
    name: "Francis Park",
    email: "Garrison@moebiuslogistics.co",
    date_of_birth: "24 Jan 1987",
    position: "Market Center Manager",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '45000',
    employment_date: '9 Dec 2015',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Latino or Hispanic',
    gender: 'Female',
    job_name: 'Account Executive',
    risk_of_exit: 19.0,
    compa_ratio: 68.5,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 3,
    name: "Adrian Kirkland",
    email: "Wilkinson@moebiuslogistics.co",
    date_of_birth: "15 Feb 1987",
    position: "Senior Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '10000',
    employment_date: '9 Jan 2021',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Asian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 8.8,
    compa_ratio: 76.4,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 5',
  },
  {
    key: 4,
    name: "Tobias Frank",
    email: "Ellison@moebiuslogistics.co",
    date_of_birth: "12 Sep 1988",
    position: "Senior Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '55000',
    employment_date: '9 Dec 2005',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 45.8,
    compa_ratio: 34.8,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 5,
    name: "Oscar Ball",
    email: "Davidson@moebiuslogistics.co",
    date_of_birth: "20 Feb 1988",
    position: "Senior Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '55000',
    employment_date: '9 Feb 2015',
    employment_status: 'active',
    employment_type: 'Part-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 87.3,
    compa_ratio: 77.3,
    scheduled_hours: '4',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 3',
  },
  {
    key: 6,
    name: "Barclay Hewitt",
    email: "Potter@moebiuslogistics.co",
    date_of_birth: "7 Jul 1972",
    position: "Senior Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '94000',
    employment_date: '12 Dec 2012',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 78.8,
    compa_ratio: 23.1,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 7,
    name: "Fitzgerald Padilla",
    email: "Vincent@moebiuslogistics.co",
    date_of_birth: "13 Mar 1976",
    position: "Senior Market Center Specialist",
    department: "Market Center",
    contract_type: 'Casual employment',
    salary: '87000',
    employment_date: '8 Mar 2015',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Female',
    job_name: 'Account Executive',
    risk_of_exit: 23.4,
    compa_ratio: 12.0,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 8,
    name: "Ciaran Shelton",
    email: "Horn@moebiuslogistics.co",
    date_of_birth: "10 Dec 1986",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '45000',
    employment_date: '10 Dec 2008',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 19.1,
    compa_ratio: 43.3,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 9,
    name: "Holmes Kelley",
    email: "Kelley@moebiuslogistics.co",
    date_of_birth: "16 Dec 1966",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '35000',
    employment_date: '10 Feb 2015',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Asian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 23.5,
    compa_ratio: 17.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 10,
    name: "Luke Thornton",
    email: "Thornton@moebiuslogistics.co",
    date_of_birth: "29 Apr 1976",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '105000',
    employment_date: '9 Jan 2021',
    employment_status: 'active',
    employment_type: 'Temporary',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 66.7,
    compa_ratio: 2.5,
    scheduled_hours: '6',
    potential: 'low',
    permanent: 'permanent',
    performance_rating: 'Level 3',
  },
  {
    key: 11,
    name: "Kasimir Lyons",
    email: "Nieves@moebiuslogistics.co",
    date_of_birth: "12 Mar 1979",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '40000',
    employment_date: '25 Jan 2006',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 6.7,
    compa_ratio: 92.8,
    scheduled_hours: '6',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 12,
    name: "Fuller Stewart",
    email: "Dudley@moebiuslogistics.co",
    date_of_birth: "9 Nov 1971",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '40000',
    employment_date: '5 Jan 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 7.7,
    compa_ratio: 87.4,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 13,
    name: "Wylie Whitley",
    email: "Martin@moebiuslogistics.co",
    date_of_birth: "12 Sep 1981",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '55000',
    employment_date: '5 Oct 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 8.3,
    compa_ratio: 88.2,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 14,
    name: "Marshall Pope",
    email: "Schultz@moebiuslogistics.co",
    date_of_birth: "9 Sep 1982",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '55000',
    employment_date: '5 Jan 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 6.3,
    compa_ratio: 84.9,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 15,
    name: "Hu Bond",
    email: "Russell@moebiuslogistics.co",
    date_of_birth: "21 Feb 1971",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '55000',
    employment_date: '5 Mar 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.3,
    compa_ratio: 82.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 16,
    name: "Hoyt Hess",
    email: "Pratt@moebiuslogistics.co",
    date_of_birth: "3 Sep 1980",
    position: "Market Center Specialist",
    department: "Market Center",
    contract_type: 'Permanent',
    salary: '65800',
    employment_date: '9 Jul 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.4,
    compa_ratio: 85.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 17,
    name: "Burke Myers",
    email: "Gallagher@moebiuslogistics.co",
    date_of_birth: "9 May 1977",
    position: "Director of Human Resources",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '20000',
    employment_date: '9 Jun 2004',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.2,
    compa_ratio: 90.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 18,
    name: "Louis Ramos",
    email: "Olsen@moebiuslogistics.co",
    date_of_birth: "9 Aug 1969",
    position: "Human Resources Manager",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '20000',
    employment_date: '13 Jan 2009',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.3,
    compa_ratio: 97.1,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 19,
    name: "Lawrence Mcclure",
    email: "Ramos@moebiuslogistics.co",
    date_of_birth: "12 Jul 1975",
    position: "Human Resources Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '340000',
    employment_date: '12 Jul 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Female',
    job_name: 'Account Executive',
    risk_of_exit: 6.9,
    compa_ratio: 89.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 20,
    name: "Scott Hill",
    email: "Wolf@moebiuslogistics.co",
    date_of_birth: "12 May 1987",
    position: "Human Resources Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '200000',
    employment_date: '9 Feb 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 13.7,
    compa_ratio: 98.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 21,
    name: "Martin Barnes",
    email: "Walton@moebiuslogistics.co",
    date_of_birth: "3 Mar 1984",
    position: "Human Resources Business Partner",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '200000',
    employment_date: '9 Mar 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 4.5,
    compa_ratio: 78.3,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 22,
    name: "Emery Price",
    email: "Carroll@moebiuslogistics.co",
    date_of_birth: "5 Dec 1986",
    position: "Human Resources Business Partner",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '20000',
    employment_date: '9 Jun 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.7,
    compa_ratio: 64.3,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 23,
    name: "Nash Reilly",
    email: "Bridges@moebiuslogistics.co",
    date_of_birth: "9 Apr 1975",
    position: "Director of Operation",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '200000',
    employment_date: '9 Jul 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 5.3,
    compa_ratio: 97.7,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 24,
    name: "Keith Espinoza",
    email: "Guzman@moebiuslogistics.co",
    date_of_birth: "17 Sep 1980",
    position: "Operation Manager",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '21 Feb 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.9,
    compa_ratio: 87.3,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 25,
    name: "Russell Yang",
    email: "Patterson@moebiuslogistics.co",
    date_of_birth: "17 Feb 1980",
    position: "Operation Manager",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '30 Apr 2016',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 4.4,
    compa_ratio: 77.4,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 26,
    name: "Berk Boyle",
    email: "Buckley@moebiuslogistics.co",
    date_of_birth: "17 Jan 1983",
    position: "Operation Specialist",
    department: "Administrative Center",
    "team": "Operation department",
    contract_type: 'Permanent',
    salary: '20000',
    employment_date: '9 Jan 2018',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.3,
    compa_ratio: 84.8,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 27,
    name: "Curran Alexander",
    email: "Moss@moebiuslogistics.co",
    date_of_birth: "23 Jan 1986",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '15 Dec 2019',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.3,
    compa_ratio: 99.5,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 28,
    name: "Darius Clayton",
    email: "Clay@moebiuslogistics.co",
    date_of_birth: "17 Jul 1979",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '23 Sep 2017',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.9,
    compa_ratio: 87.9,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 29,
    name: "Warren Vincent",
    email: "Marks@moebiuslogistics.co",
    date_of_birth: "21 Nov 1987",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '9 Mar 2020',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.4,
    compa_ratio: 79.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 30,
    name: "Uriah Watson",
    email: "Stanton@moebiuslogistics.co",
    date_of_birth: "21 Nov 1981",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '9 Jul 2005',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.5,
    compa_ratio: 87.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 31,
    name: "Porter Higgins",
    email: "Jacobson@moebiuslogistics.co",
    date_of_birth: "1 Jul 1989",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '31 May 2020',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.5,
    compa_ratio: 88.4,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 32,
    name: "Geoffrey Pacheco",
    email: "Gomez@moebiuslogistics.co",
    date_of_birth: "1 Feb 1980",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '29 May 2019',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.8,
    compa_ratio: 99.2,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 33,
    name: "Gray Pierce",
    email: "Oconnor@moebiuslogistics.co",
    date_of_birth: "17 Mar 1983",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '18 Sep 2001',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.9,
    compa_ratio: 88.1,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 34,
    name: "Sawyer Curtis",
    email: "Schneider@moebiuslogistics.co",
    date_of_birth: "1 Sep 1987",
    position: "Operation Specialist",
    department: "Administrative Center",
    contract_type: 'Permanent',
    salary: '340000',
    employment_date: '14 Nov 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.8,
    compa_ratio: 87.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 35,
    name: "Rashad Hancock",
    email: "Justice@moebiuslogistics.co",
    date_of_birth: "17 Jul 1976",
    position: "Director of Sales",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '17 Jul 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.4,
    compa_ratio: 90.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 36,
    name: "Alvin Donovan",
    email: "Bond@moebiuslogistics.co",
    date_of_birth: "1 Sep 1976",
    position: "Account Manager",
    department: "Customer Service department",
    "team": "Sales Account Service",
    contract_type: 'Permanent',
    salary: '340000',
    employment_date: '19 Nov 2011',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.3,
    compa_ratio: 93.1,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 37,
    name: "Yoshio James",
    email: "Kemp@moebiuslogistics.co",
    date_of_birth: "1 Oct 1989",
    position: "Account Manager",
    department: "Customer Service department",
    "team": "Sales Account Service",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '9 Nov 2009',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.9,
    compa_ratio: 76.4,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 38,
    name: "Joseph Lynn",
    email: "Navarro@moebiuslogistics.co",
    date_of_birth: "1 Oct 1986",
    position: "Account Manager",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '55900',
    employment_date: '9 Jul 2004',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.3,
    compa_ratio: 97.3,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 39,
    name: "Elton Buck",
    email: "Randolph@moebiuslogistics.co",
    date_of_birth: "21 Sep 1966",
    position: "Account Manager",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '340000',
    employment_date: '26 Nov 2003',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.9,
    compa_ratio: 98.7,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 40,
    name: "Jesse Carey",
    email: "Tanner@moebiuslogistics.co",
    date_of_birth: "1 Sep 1969",
    position: "Account Manager",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '9 May 2009',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 2.9,
    compa_ratio: 93.7,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 41,
    name: "Gage Puckett",
    email: "Herman@moebiuslogistics.co",
    date_of_birth: "23 Jul 1965",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '590000',
    employment_date: '17 Sep 2007',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 3.4,
    compa_ratio: 66.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 42,
    name: "Ryder Morgan",
    email: "Colon@moebiuslogistics.co",
    date_of_birth: "19 Nov 1985",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '349000',
    employment_date: '23 Jan 2010',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 4.9,
    compa_ratio: 95.1,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 43,
    name: "Orson Clayton",
    email: "Small@moebiuslogistics.co",
    date_of_birth: "21 Jul 1989",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '54500',
    employment_date: '29 Nov 2019',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 4.5,
    compa_ratio: 91.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 44,
    name: "Griffith Reeves",
    email: "Schneider@moebiuslogistics.co",
    date_of_birth: "19 Mar 1983",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '87500',
    employment_date: '12 Sep 2012',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 4.8,
    compa_ratio: 78.0,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 45,
    name: "Barclay Vincent",
    email: "Joyner@moebiuslogistics.co",
    date_of_birth: "21 Dec 1989",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '10000',
    employment_date: '9 Jun 2014',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 67.1,
    compa_ratio: 45.9,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 46,
    name: "Vaughan Dalton",
    email: "Gibson@moebiuslogistics.co",
    date_of_birth: "23 Sep 1988",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '665000',
    employment_date: '29 Apr 2018',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 1.6,
    compa_ratio: 98.6,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 47,
    name: "Silas Ellis",
    email: "Head@moebiuslogistics.co",
    date_of_birth: "21 Apr 1969",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '50000',
    employment_date: '9 Mar 2009',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Female',
    job_name: 'Account Executive',
    risk_of_exit: 12.8,
    compa_ratio: 79.9,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 48,
    name: "Colin Lancaster",
    email: "Mcgowan@moebiuslogistics.co",
    date_of_birth: "17 Oct 1965",
    position: "Account Executive",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '230000',
    employment_date: '28 Feb 2001',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Female',
    job_name: 'Account Executive',
    risk_of_exit: 3.0,
    compa_ratio: 93.8,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 49,
    name: "Rigel Mclean",
    email: "Giles@moebiuslogistics.co",
    date_of_birth: "1 Nov 1987",
    position: "Customer Service Manager",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '980000',
    employment_date: '9 Nov 2019',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Female',
    job_name: 'Account Executive',
    risk_of_exit: 5.2,
    compa_ratio: 81.7,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  },
  {
    key: 50,
    name: "Brandon Hernandez",
    email: "Walsh@moebiuslogistics.co",
    date_of_birth: "19 Oct 1967",
    position: "Customer Service Specialist",
    department: "Customer Service department",
    contract_type: 'Permanent',
    salary: '340000',
    employment_date: '2 Dec 2010',
    employment_status: 'active',
    employment_type: 'Full-Time',
    ethnicity: 'Hawaiian',
    gender: 'Male',
    job_name: 'Account Executive',
    risk_of_exit: 8.1,
    compa_ratio: 76.8,
    scheduled_hours: '8',
    potential: 'medium',
    permanent: 'permanent',
    performance_rating: 'Level 4',
  }
];


// Analysis

export const tabs = [
  {
    id: '1',
    name: 'Overview',
    isActive: false,
  }, {
    id: '2',
    name: 'Organisation',
    isActive: false,
  }, {
    id: '3',
    name: 'Finance',
    isActive: false,
  }, {
    id: '4',
    name: 'Workforce',
    isActive: true,
  }, {
    id: '5',
    name: 'Planning',
    isActive: false,
  }, {
    id: '6',
    name: 'Analysis',
    isActive: false,
  },
];


export const currentUser = {
  name: 'Daniel Aduszkiewicz',
  email: 'dan@humanpanel.com',
};

export const options = [
  {
    id: '1',
    name: 'Employees',
    value: 'employees',
  }, {
    id: '2',
    name: 'Custom Service',
    value: 'custom-service',
  }, {
    id: '3',
    name: 'Sales Account Service',
    value: 'sales-account-service',
  }, {
    id: '4',
    name: 'Management level',
    value: 'management-level',
  },
];

export const compareValues = [
  {
    id: '0',
    name: '',
    key: 'name'
  },
  {
    id: '1',
    name: 'Age',
    key: 'age'
  }, {
    id: '2',
    name: 'Birth Date',
    key: 'date_of_birth'
  }, {
    id: '3',
    name: 'Contract Type',
    key: 'contract_type'
  }, {
    id: '4',
    name: 'Email Address',
    key: 'email'
  }, {
    id: '5',
    name: 'Employment Status',
    key: 'employment_status'
  }, {
    id: '6',
    name: 'Employment Type',
    key: 'employment_type'
  }, {
    id: '7',
    name: 'Ethnicity',
    key: 'ethnicity'
  }, {
    id: '8',
    name: 'Gender',
    key: 'gender'
  }, {
    id: '9',
    name: 'Job Name',
    key: 'job_name'
  }, {
    id: '10',
    name: 'Risk of Exit',
    key: 'risk_of_exit'
  }, {
    id: '11',
    name: 'Compa Ratio',
    key: 'compa_ratio'
  }, {
    id: '12',
    name: 'Tenure',
    key: 'tenure'
  }, {
    id: '13',
    name: 'Start Date',
    key: 'employment_date'
  }, {
    id: '14',
    name: 'Scheduled Hours',
    key: 'scheduled_hours'
  }, {
    id: '15',
    name: 'Potential',
    key: 'potential'
  }, {
    id: '16',
    name: 'Permanent',
    key: 'permanent'
  }, {
    id: '17',
    name: 'Performance rating',
    key: 'performance_rating'
  }, {
    id: '18',
    name: 'Overtime status',
    key: 'overtime_status'
  },
];